# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests and push the image to the private docker repo and send a slack notification
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: setup node 
      uses: actions/setup-node@v3
      
    - name: Install dependencies
      run: npm ci

    - name: build and run test
      run: npm test

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
  
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: akshaya90/akshaya-personal-repo
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
    env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    if: always()  # Pick up events even if the job fails or is canceled.
        
        
        
        
        
        
